### PR TITLE
Matio is required

### PR DESCRIPTION
**Pull request by mjacob75**
In order to build PowerGrid it is required that you need Matio.
This patch makes it easier for new usersto find Matio libraries.

### CODE REVIEW

**Comment by mjacob75** [comment]
@acerjanic,@hjmjohnson 
Alex,

I am just trying to install Powergrid on my computer. I made a small modification to the cMakeLists. Please review it. 

Mathews & Hans

**Comment by hjmjohnson** [comment]
@mjacob75  Thank you.  There are a few other changes that should be made for other packages as well.  I can help with those if you want me to help.

Hans

**Comment by mjacob75** [comment]
Sure. That would be helpful.

**Comment by acerjanic** [comment]
Hi Drs. Jacobs and Johnson, 

I think this change makes sense. I've gone ahead and merged it in. I've seen the other PR for the other changes, so I'll take a look at those issues in #4 .

Thanks,

Alex

**Pull request merged**
