### PR TITLE
Cmake cleanup

### PR DESCRIPTION
**Pull request by hjmjohnson**
@mjacobs75 This is some more cleanup for the build process. I still don't have the build working due to dependencies on a package called xsd.

PowerGrid/PowerGrid/config.hxx:50:10: fatal error: 'xsd/cxx/config.hxx' file not found
# include <xsd/cxx/config.hxx>

### CODE REVIEW

**Comment by acerjanic** [comment]
@hjmjohnson Thanks for pointing out some of the issues with our CMake configuration. These changes make sense, and explain why I was having trouble with the C++11 configuration in the past.

I need to update our website (mrfil.github.io/PowerGrid) for the XSD dependency. Apparently, I forgot that in the list when I wrote that documentation page. If you are on Ubuntu (a recent version 14.04 or higher, if memory serves), you can just install the xsdcxx package with apt-get.

Before I merge in this PR, I'd like to test this against our vagrantfile so I can make those changes. I'm traveling today, and I have spotty internet access, so I hope to get to it tomorrow.

**Comment by hjmjohnson** [comment]
@mjacob75 
@acerjanic   We are not on ubuntu, and we do not have root level access to the machines that we are using.  It will be great to have documentation about how to use XSD.

**Comment by acerjanic** [comment]
@hjmjohnson @mjacob75 

You can build XSD from source using the instructions [here](http://www.codesynthesis.com/projects/xsd/extras/build-unix.xhtml) and download a source tarball from [here](http://www.codesynthesis.com/products/xsd/download.xhtml). 

It uses the old fashioned make and configure scripts, (it's been a while since I've done this but  if I remember correctly) you can pass a --prefix=/home/somewhere directory and create a local build there. I think that there isn't a shared library component, just a set of headers that need to be accessible at build time, I believe. This is what we did on Blue Waters.

I tested your PR and it worked in our Vagrant dev environment, so I'll go ahead and merge in the PR. Thanks for your help and efforts to improve our CMake files.

**Comment by hjmjohnson** [comment]
@mjacob75
 git clone git://scm.codesynthesis.com/xsd.git

**Comment by acerjanic** [comment]
@hjmjohnson @mjacob75 

I want to point out my mistake before you waste too much time. You don't need to build XSD from scratch in your situation. If you download the tar.bz2 archive from [this page](http://www.codesynthesis.com/products/xsd/download.xhtml) you can simply unarchive it and make sure that the libxsd subdirectory shows up on the search path for include files. 

When we were building on Blue Waters, our team had shared directory where the packages were built including a path for includes. We put the xsd (in the libxsd folder in the tar.bz2 archive) includes in that directory, which was on our include search path for the other required packages. 

If you need more help, let me know. Again, sorry for leading you down the wrong direction there. It's been over a year since I've had to deal with setting this on Blue Waters.

**Pull request merged**
